"""
Standalone 3D Artery Reconstruction Viewer
==========================================

Loads the OBJ generated by scripts/dicom_3d_pipeline.py and displays the
reconstructed artery tree with branch-confidence colors and QCA/radius metrics.

Usage:
    python src/artery_3d_viewer.py
    python src/artery_3d_viewer.py --obj dicom_pipeline_output_v2/pipeline_hybrid_qca_tree.obj
"""

from __future__ import annotations

import argparse
import csv
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import (
    QApplication,
    QFileDialog,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QMainWindow,
    QMessageBox,
    QPushButton,
    QTableWidget,
    QTableWidgetItem,
    QVBoxLayout,
    QWidget,
)

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from mpl_toolkits.mplot3d.art3d import Poly3DCollection


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OBJ = PROJECT_ROOT / "dicom_pipeline_output_v2" / "pipeline_hybrid_qca_tree.obj"


MATERIAL_COLORS = {
    "reliable": (0.78, 0.78, 0.78, 1.0),
    "usable": (0.35, 0.55, 1.0, 1.0),
    "single_view_preserved": (1.0, 0.58, 0.12, 1.0),
    "stenosis_marker": (1.0, 0.02, 0.02, 1.0),
}


@dataclass
class ObjPart:
    name: str
    material: str = "reliable"
    faces: List[List[int]] = field(default_factory=list)


@dataclass
class ObjMesh:
    vertices: np.ndarray
    parts: List[ObjPart]


def parse_obj(path: Path) -> ObjMesh:
    vertices: List[Tuple[float, float, float]] = []
    parts: List[ObjPart] = []
    current = ObjPart(name="mesh")

    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            fields = line.split()
            if fields[0] == "o":
                if current.faces:
                    parts.append(current)
                current = ObjPart(name=" ".join(fields[1:]) or f"part_{len(parts)}")
            elif fields[0] == "usemtl":
                current.material = fields[1] if len(fields) > 1 else "reliable"
            elif fields[0] == "v" and len(fields) >= 4:
                vertices.append((float(fields[1]), float(fields[2]), float(fields[3])))
            elif fields[0] == "f" and len(fields) >= 4:
                face = []
                for token in fields[1:]:
                    idx = int(token.split("/")[0])
                    if idx < 0:
                        idx = len(vertices) + 1 + idx
                    face.append(idx - 1)
                if len(face) >= 3:
                    current.faces.append(face)

    if current.faces:
        parts.append(current)
    if not vertices or not parts:
        raise ValueError(f"No renderable OBJ geometry found: {path}")
    return ObjMesh(vertices=np.asarray(vertices, dtype=np.float32), parts=parts)


def load_branch_report(obj_path: Path) -> Dict[int, Dict[str, str]]:
    candidates = [
        obj_path.with_name("pipeline_branch_quality_radius.csv"),
        obj_path.with_name("hybrid_qca_radius_report.csv"),
        obj_path.with_name("branch_quality_report.csv"),
    ]
    for csv_path in candidates:
        if csv_path.exists():
            with open(csv_path, newline="", encoding="utf-8") as f:
                rows = list(csv.DictReader(f))
            report = {}
            for row in rows:
                try:
                    report[int(row["branch_id"])] = row
                except Exception:
                    continue
            return report
    return {}


def branch_id_from_name(name: str) -> Optional[int]:
    match = re.search(r"branch[_-](\d+)", name)
    if not match:
        return None
    return int(match.group(1))


def format_number(value: Optional[str], decimals: int = 2) -> str:
    if value is None or value == "":
        return ""
    try:
        return f"{float(value):.{decimals}f}"
    except Exception:
        return str(value)


class Artery3DViewer(QMainWindow):
    def __init__(self, initial_obj: Optional[Path] = None):
        super().__init__()
        self.setWindowTitle("3D Artery Reconstruction Viewer")
        self.resize(1320, 820)

        self.obj_path: Optional[Path] = None
        self.mesh: Optional[ObjMesh] = None
        self.report: Dict[int, Dict[str, str]] = {}
        self.collections: Dict[int, List[Poly3DCollection]] = {}

        self.figure = Figure(figsize=(8, 7))
        self.canvas = FigureCanvas(self.figure)
        self.ax = self.figure.add_subplot(111, projection="3d")

        self.lbl_path = QLabel("No OBJ loaded")
        self.lbl_path.setTextInteractionFlags(Qt.TextSelectableByMouse)

        self.btn_open = QPushButton("Open OBJ")
        self.btn_open.clicked.connect(self.open_obj_dialog)
        self.btn_reset = QPushButton("Reset View")
        self.btn_reset.clicked.connect(self.reset_view)

        self.table = QTableWidget(0, 7)
        self.table.setHorizontalHeaderLabels(
            ["Branch", "Status", "DS %", "Min R mm", "Ref R mm", "Median Err", "P90 Err"]
        )
        self.table.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.table.setSelectionBehavior(QTableWidget.SelectRows)
        self.table.itemSelectionChanged.connect(self.highlight_selected_branch)

        right_panel = QVBoxLayout()
        right_panel.addWidget(QLabel("Branch Quality / Radius"))
        right_panel.addWidget(self.table)

        controls = QHBoxLayout()
        controls.addWidget(self.btn_open)
        controls.addWidget(self.btn_reset)
        controls.addStretch(1)

        left_panel = QVBoxLayout()
        left_panel.addLayout(controls)
        left_panel.addWidget(self.lbl_path)
        left_panel.addWidget(self.canvas, stretch=1)

        layout = QHBoxLayout()
        layout.addLayout(left_panel, stretch=4)
        layout.addLayout(right_panel, stretch=2)

        root = QWidget()
        root.setLayout(layout)
        self.setCentralWidget(root)

        if initial_obj and initial_obj.exists():
            self.load_obj(initial_obj)
        elif DEFAULT_OBJ.exists():
            self.load_obj(DEFAULT_OBJ)

    def open_obj_dialog(self):
        path, _ = QFileDialog.getOpenFileName(
            self,
            "Open artery OBJ",
            str(PROJECT_ROOT),
            "OBJ Files (*.obj);;All Files (*)",
        )
        if path:
            self.load_obj(Path(path))

    def load_obj(self, path: Path):
        try:
            self.mesh = parse_obj(path)
            self.report = load_branch_report(path)
            self.obj_path = path
            self.lbl_path.setText(str(path))
            self.populate_table()
            self.render_mesh()
        except Exception as exc:
            QMessageBox.critical(self, "Failed to load OBJ", str(exc))

    def populate_table(self):
        self.table.setRowCount(0)
        if not self.mesh:
            return

        branch_ids = sorted(
            branch_id
            for branch_id in {branch_id_from_name(part.name) for part in self.mesh.parts}
            if branch_id is not None
        )
        for row_idx, branch_id in enumerate(branch_ids):
            row = self.report.get(branch_id, {})
            status = row.get("status", self.status_from_parts(branch_id))
            values = [
                str(branch_id),
                status,
                format_number(row.get("estimated_diameter_stenosis_pct"), 1),
                format_number(row.get("min_radius_mm"), 3),
                format_number(row.get("ref_radius_mm_p80"), 3),
                format_number(row.get("median_residual_mm"), 2),
                format_number(row.get("p90_residual_mm"), 2),
            ]
            self.table.insertRow(row_idx)
            for col_idx, value in enumerate(values):
                item = QTableWidgetItem(value)
                if col_idx == 0:
                    item.setData(Qt.UserRole, branch_id)
                self.table.setItem(row_idx, col_idx, item)

    def status_from_parts(self, branch_id: int) -> str:
        if not self.mesh:
            return ""
        for part in self.mesh.parts:
            if branch_id_from_name(part.name) == branch_id:
                return part.material
        return ""

    def render_mesh(self):
        if not self.mesh:
            return
        self.ax.clear()
        self.collections = {}
        verts = self.mesh.vertices

        for part in self.mesh.parts:
            polygons = [verts[face] for face in part.faces if len(face) >= 3]
            if not polygons:
                continue
            color = MATERIAL_COLORS.get(part.material, (0.75, 0.75, 0.75, 1.0))
            collection = Poly3DCollection(
                polygons,
                facecolor=color,
                edgecolor=(0.25, 0.25, 0.25, 0.18),
                linewidths=0.15,
                alpha=color[3],
            )
            self.ax.add_collection3d(collection)
            branch_id = branch_id_from_name(part.name)
            if branch_id is not None:
                self.collections.setdefault(branch_id, []).append(collection)

        self.set_equal_axes(verts)
        self.ax.set_title("3D Artery Tree")
        self.ax.set_xlabel("X mm")
        self.ax.set_ylabel("Y mm")
        self.ax.set_zlabel("Z mm")
        self.ax.view_init(elev=25, azim=-60)
        self.figure.tight_layout()
        self.canvas.draw_idle()

    def set_equal_axes(self, verts: np.ndarray):
        mins = verts.min(axis=0)
        maxs = verts.max(axis=0)
        center = (mins + maxs) / 2.0
        radius = max(float(np.max(maxs - mins)) / 2.0, 1.0)
        self.ax.set_xlim(center[0] - radius, center[0] + radius)
        self.ax.set_ylim(center[1] - radius, center[1] + radius)
        self.ax.set_zlim(center[2] - radius, center[2] + radius)

    def reset_view(self):
        if self.mesh:
            self.set_equal_axes(self.mesh.vertices)
            self.ax.view_init(elev=25, azim=-60)
            self.canvas.draw_idle()

    def highlight_selected_branch(self):
        if not self.mesh:
            return

        selected_items = self.table.selectedItems()
        selected_branch = None
        if selected_items:
            selected_branch = self.table.item(selected_items[0].row(), 0).data(Qt.UserRole)

        for branch_id, collections in self.collections.items():
            for collection in collections:
                if selected_branch is not None and branch_id == selected_branch:
                    collection.set_edgecolor((1.0, 0.0, 0.0, 1.0))
                    collection.set_linewidth(0.9)
                    collection.set_alpha(1.0)
                else:
                    collection.set_edgecolor((0.25, 0.25, 0.25, 0.18))
                    collection.set_linewidth(0.15)
        self.canvas.draw_idle()


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--obj", type=Path, default=DEFAULT_OBJ, help="Path to reconstructed artery OBJ")
    return parser.parse_args()


def main():
    args = parse_args()
    os.environ.setdefault("QT_ENABLE_HIGHDPI_SCALING", "1")
    app = QApplication(sys.argv)
    viewer = Artery3DViewer(args.obj)
    viewer.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
