"""
VTK 3D Artery Reconstruction Viewer
===================================

Blender-like standalone viewer for the OBJ generated by the DICOM-to-3D
pipeline. Uses VTK's native trackball camera interaction:

- Left mouse: rotate/orbit
- Mouse wheel: zoom
- Middle/right mouse: pan, depending on mouse/VTK settings
- Click a row in the table to highlight a branch

Usage:
    python src/artery_3d_vtk_viewer.py
    python src/artery_3d_vtk_viewer.py --obj dicom_pipeline_output_v2/pipeline_hybrid_qca_tree.obj
"""

from __future__ import annotations

import argparse
import csv
import math
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Keep the viewer lightweight on laptops/older workstations. Some scientific
# wheels initialize OpenBLAS even when the viewer itself is not doing heavy math.
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")

from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import (
    QApplication,
    QComboBox,
    QDoubleSpinBox,
    QFileDialog,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QMainWindow,
    QMessageBox,
    QPushButton,
    QTableWidget,
    QTableWidgetItem,
    QTabWidget,
    QVBoxLayout,
    QWidget,
)

import vtk
from vtkmodules.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor

try:
    import numpy as np
except Exception:  # pragma: no cover - numpy is expected in this project
    np = None


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OBJ = PROJECT_ROOT / "dicom_pipeline_output_v2" / "pipeline_hybrid_qca_tree.obj"


MATERIAL_COLORS = {
    "reliable": (0.78, 0.78, 0.78),
    "usable": (0.25, 0.48, 1.0),
    "single_view_preserved": (1.0, 0.55, 0.08),
    "stenosis_marker": (1.0, 0.02, 0.02),
}


@dataclass
class ObjPart:
    name: str
    material: str = "reliable"
    faces: List[List[int]] = field(default_factory=list)


@dataclass
class ObjMesh:
    vertices: List[Tuple[float, float, float]]
    parts: List[ObjPart]


def parse_obj(path: Path) -> ObjMesh:
    vertices: List[Tuple[float, float, float]] = []
    parts: List[ObjPart] = []
    current = ObjPart(name="mesh")

    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            fields = line.split()
            if fields[0] == "o":
                if current.faces:
                    parts.append(current)
                current = ObjPart(name=" ".join(fields[1:]) or f"part_{len(parts)}")
            elif fields[0] == "usemtl":
                current.material = fields[1] if len(fields) > 1 else "reliable"
            elif fields[0] == "v" and len(fields) >= 4:
                vertices.append((float(fields[1]), float(fields[2]), float(fields[3])))
            elif fields[0] == "f" and len(fields) >= 4:
                face = []
                for token in fields[1:]:
                    idx = int(token.split("/")[0])
                    if idx < 0:
                        idx = len(vertices) + 1 + idx
                    face.append(idx - 1)
                if len(face) >= 3:
                    current.faces.append(face)

    if current.faces:
        parts.append(current)
    if not vertices or not parts:
        raise ValueError(f"No renderable OBJ geometry found: {path}")
    return ObjMesh(vertices=vertices, parts=parts)


def load_branch_report(obj_path: Path) -> Dict[int, Dict[str, str]]:
    candidates = [
        obj_path.with_name("pipeline_branch_quality_radius.csv"),
        obj_path.with_name("hybrid_qca_radius_report.csv"),
        obj_path.with_name("branch_quality_report.csv"),
    ]
    for csv_path in candidates:
        if csv_path.exists():
            with open(csv_path, newline="", encoding="utf-8") as f:
                rows = list(csv.DictReader(f))
            report = {}
            for row in rows:
                try:
                    report[int(row["branch_id"])] = row
                except Exception:
                    continue
            return report
    return {}


def branch_id_from_name(name: str) -> Optional[int]:
    match = re.search(r"branch[_-](\d+)", name)
    return int(match.group(1)) if match else None


def format_number(value: Optional[str], decimals: int = 2) -> str:
    if value is None or value == "":
        return ""
    try:
        return f"{float(value):.{decimals}f}"
    except Exception:
        return str(value)


def make_polydata(vertices: List[Tuple[float, float, float]], faces: List[List[int]]) -> vtk.vtkPolyData:
    points = vtk.vtkPoints()
    used_map: Dict[int, int] = {}

    for face in faces:
        for idx in face:
            if idx not in used_map:
                used_map[idx] = points.InsertNextPoint(vertices[idx])

    cells = vtk.vtkCellArray()
    for face in faces:
        if len(face) < 3:
            continue
        cells.InsertNextCell(len(face))
        for idx in face:
            cells.InsertCellPoint(used_map[idx])

    poly = vtk.vtkPolyData()
    poly.SetPoints(points)
    poly.SetPolys(cells)

    normals = vtk.vtkPolyDataNormals()
    normals.SetInputData(poly)
    normals.ConsistencyOn()
    normals.SplittingOff()
    normals.Update()
    return normals.GetOutput()


class VTKArteryViewer(QMainWindow):
    def __init__(self, initial_obj: Optional[Path] = None):
        super().__init__()
        self.setWindowTitle("3D Artery Viewer - VTK")
        self.resize(1450, 900)

        self.obj_path: Optional[Path] = None
        self.mesh: Optional[ObjMesh] = None
        self.report: Dict[int, Dict[str, str]] = {}
        self.summary: Dict[str, object] = {}
        self.branch_actors: Dict[int, List[vtk.vtkActor]] = {}
        self.all_actors: List[vtk.vtkActor] = []
        self.orientation_widget: Optional[vtk.vtkOrientationMarkerWidget] = None

        self.vtk_widget = QVTKRenderWindowInteractor(self)
        self.renderer = vtk.vtkRenderer()
        self.renderer.SetBackground(0.075, 0.08, 0.09)
        self.vtk_widget.GetRenderWindow().AddRenderer(self.renderer)
        self.interactor = self.vtk_widget.GetRenderWindow().GetInteractor()
        style = vtk.vtkInteractorStyleTrackballCamera()
        self.interactor.SetInteractorStyle(style)

        self.lbl_path = QLabel("No OBJ loaded")
        self.lbl_path.setTextInteractionFlags(Qt.TextSelectableByMouse)

        self.btn_open = QPushButton("Open OBJ")
        self.btn_open.clicked.connect(self.open_obj_dialog)
        self.btn_reset = QPushButton("Reset Camera")
        self.btn_reset.clicked.connect(self.reset_camera)
        self.btn_top = QPushButton("IM0-like View")
        self.btn_top.clicked.connect(self.set_im0_like_view)
        self.btn_view_a = QPushButton("View A Angle")
        self.btn_view_a.clicked.connect(lambda: self.set_summary_angle_view("view_a"))
        self.btn_view_b = QPushButton("View B Angle")
        self.btn_view_b.clicked.connect(lambda: self.set_summary_angle_view("view_b"))
        self.spin_primary = QDoubleSpinBox()
        self.spin_primary.setRange(-180.0, 180.0)
        self.spin_primary.setDecimals(1)
        self.spin_primary.setSuffix(" P")
        self.spin_primary.setFixedWidth(90)
        self.spin_secondary = QDoubleSpinBox()
        self.spin_secondary.setRange(-180.0, 180.0)
        self.spin_secondary.setDecimals(1)
        self.spin_secondary.setSuffix(" S")
        self.spin_secondary.setFixedWidth(90)
        self.btn_apply_angle = QPushButton("Apply Angle")
        self.btn_apply_angle.clicked.connect(self.apply_manual_angle_view)
        self.combo_image_orientation = QComboBox()
        self.combo_image_orientation.addItems(
            [
                "Rotate 180",
                "Normal",
                "Mirror H",
                "Mirror V",
                "Mirror H + Rotate 180",
                "Mirror V + Rotate 180",
                "Opposite Side",
                "Opposite Side + Rotate 180",
            ]
        )
        self.combo_image_orientation.setFixedWidth(175)
        self.combo_image_orientation.currentIndexChanged.connect(self.apply_manual_angle_view)

        self.table = QTableWidget(0, 7)
        self.table.setHorizontalHeaderLabels(["Branch", "Status", "DS %", "Min R", "Ref R", "Median Err", "P90 Err"])
        self.table.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.table.setSelectionBehavior(QTableWidget.SelectRows)
        self.table.itemSelectionChanged.connect(self.highlight_selected_branch)

        self.lbl_summary = QLabel("No pipeline summary loaded")
        self.lbl_summary.setWordWrap(True)
        self.lbl_summary.setTextInteractionFlags(Qt.TextSelectableByMouse)

        self.combo_overlay = QComboBox()
        self.combo_overlay.currentIndexChanged.connect(self.update_overlay_image)
        self.lbl_overlay = QLabel("No validation image")
        self.lbl_overlay.setAlignment(Qt.AlignCenter)
        self.lbl_overlay.setMinimumHeight(260)
        self.lbl_overlay.setStyleSheet("background: #111; color: #ccc;")
        self.lbl_overlay.setScaledContents(False)

        self.tabs = QTabWidget()
        table_page = QWidget()
        table_layout = QVBoxLayout()
        table_layout.addWidget(self.table)
        table_page.setLayout(table_layout)

        validation_page = QWidget()
        validation_layout = QVBoxLayout()
        validation_layout.addWidget(QLabel("Pipeline Summary"))
        validation_layout.addWidget(self.lbl_summary)
        validation_layout.addWidget(QLabel("2D Validation / Segmentation"))
        validation_layout.addWidget(self.combo_overlay)
        validation_layout.addWidget(self.lbl_overlay, stretch=1)
        validation_page.setLayout(validation_layout)

        self.tabs.addTab(table_page, "Branches")
        self.tabs.addTab(validation_page, "Validation")

        left_layout = QVBoxLayout()
        controls = QHBoxLayout()
        controls.addWidget(self.btn_open)
        controls.addWidget(self.btn_reset)
        controls.addWidget(self.btn_top)
        controls.addWidget(self.btn_view_a)
        controls.addWidget(self.btn_view_b)
        controls.addWidget(self.spin_primary)
        controls.addWidget(self.spin_secondary)
        controls.addWidget(QLabel("Image"))
        controls.addWidget(self.combo_image_orientation)
        controls.addWidget(self.btn_apply_angle)
        controls.addStretch(1)
        left_layout.addLayout(controls)
        left_layout.addWidget(self.lbl_path)
        left_layout.addWidget(self.vtk_widget, stretch=1)

        right_layout = QVBoxLayout()
        right_layout.addWidget(QLabel("Branch Quality / Validation"))
        right_layout.addWidget(self.tabs, stretch=1)
        hint = QLabel("Mouse: left rotate | wheel zoom | right/middle pan")
        hint.setStyleSheet("color: #555;")
        right_layout.addWidget(hint)

        layout = QHBoxLayout()
        layout.addLayout(left_layout, stretch=5)
        layout.addLayout(right_layout, stretch=2)

        root = QWidget()
        root.setLayout(layout)
        self.setCentralWidget(root)

        if initial_obj and initial_obj.exists():
            self.load_obj(initial_obj)
        elif DEFAULT_OBJ.exists():
            self.load_obj(DEFAULT_OBJ)

        self.interactor.Initialize()

    def open_obj_dialog(self):
        path, _ = QFileDialog.getOpenFileName(self, "Open artery OBJ", str(PROJECT_ROOT), "OBJ Files (*.obj);;All Files (*)")
        if path:
            self.load_obj(Path(path))

    def load_obj(self, path: Path):
        try:
            self.mesh = parse_obj(path)
            self.report = load_branch_report(path)
            self.summary = self.load_pipeline_summary(path)
            self.obj_path = path
            self.lbl_path.setText(str(path))
            self.populate_table()
            self.populate_validation_panel()
            self.update_angle_controls_from_summary()
            self.render_mesh()
        except Exception as exc:
            QMessageBox.critical(self, "Failed to load OBJ", str(exc))

    def populate_table(self):
        self.table.setRowCount(0)
        if not self.mesh:
            return
        branch_ids = sorted(
            branch_id
            for branch_id in {branch_id_from_name(part.name) for part in self.mesh.parts}
            if branch_id is not None
        )
        for row_idx, branch_id in enumerate(branch_ids):
            row = self.report.get(branch_id, {})
            status = row.get("status", self.status_from_parts(branch_id))
            values = [
                str(branch_id),
                status,
                format_number(row.get("estimated_diameter_stenosis_pct"), 1),
                format_number(row.get("min_radius_mm"), 3),
                format_number(row.get("ref_radius_mm_p80"), 3),
                format_number(row.get("median_residual_mm"), 2),
                format_number(row.get("p90_residual_mm"), 2),
            ]
            self.table.insertRow(row_idx)
            for col_idx, value in enumerate(values):
                item = QTableWidgetItem(value)
                if col_idx == 0:
                    item.setData(Qt.UserRole, branch_id)
                self.table.setItem(row_idx, col_idx, item)

    def status_from_parts(self, branch_id: int) -> str:
        if not self.mesh:
            return ""
        for part in self.mesh.parts:
            if branch_id_from_name(part.name) == branch_id:
                return part.material
        return ""

    def load_pipeline_summary(self, obj_path: Path) -> Dict[str, object]:
        candidates = [
            obj_path.with_name("pipeline_summary.json"),
            obj_path.with_name("hybrid_qca_radius_summary.json"),
            obj_path.with_name("filtered_epipolar_summary.json"),
            obj_path.with_name("smoothed_junction_summary.json"),
        ]
        for path in candidates:
            if path.exists():
                try:
                    import json

                    with open(path, "r", encoding="utf-8") as f:
                        return json.load(f)
                except Exception:
                    continue
        return {}

    def populate_validation_panel(self):
        self.lbl_summary.setText(self.format_summary_text())
        self.combo_overlay.blockSignals(True)
        self.combo_overlay.clear()
        for label, path in self.find_validation_images():
            self.combo_overlay.addItem(label, str(path))
        self.combo_overlay.blockSignals(False)
        self.update_overlay_image()

    def format_summary_text(self) -> str:
        if not self.summary:
            return "No summary JSON found beside this OBJ."
        lines = []
        if "branch_status_counts" in self.summary:
            counts = self.summary.get("branch_status_counts", {})
            lines.append(
                "Branches: "
                f"reliable {counts.get('reliable', 0)} | "
                f"usable {counts.get('usable', 0)} | "
                f"single-view {counts.get('single_view_preserved', 0)}"
            )
        if "num_xa_clips_found" in self.summary:
            lines.append(f"XA clips found: {self.summary.get('num_xa_clips_found')}")
        for key in ("view_a", "view_b"):
            view = self.summary.get(key)
            if isinstance(view, dict):
                lines.append(
                    f"{key}: clip {view.get('clip_index', '?')} frame {view.get('frame', '?')} "
                    f"P {view.get('primary_angle_deg', '?')} S {view.get('secondary_angle_deg', '?')}"
                )
        if "warning" in self.summary:
            lines.append(str(self.summary["warning"]))
        if not lines:
            lines.append("Summary loaded.")
        return "\n".join(lines)

    def find_validation_images(self) -> List[Tuple[str, Path]]:
        if not self.obj_path:
            return []
        folder = self.obj_path.parent
        candidates = [
            ("View A Segmentation", folder / "view_a_overlay.png"),
            ("View B Segmentation", folder / "view_b_overlay.png"),
            ("View C / IM1 Segmentation", folder / "view_c_overlay.png"),
            ("View C / IM1 Validation", folder / "view_c_im1_validation_overlay.png"),
            ("View A Mask", folder / "view_a_mask.png"),
            ("View B Mask", folder / "view_b_mask.png"),
            ("View C / IM1 Mask", folder / "view_c_mask.png"),
            ("View A Skeleton", folder / "view_a_skeleton.png"),
            ("View B Skeleton", folder / "view_b_skeleton.png"),
            ("View C / IM1 Skeleton", folder / "view_c_skeleton.png"),
            ("Filtered IM0 Reprojection", folder / "filtered_reprojection_IM0.png"),
            ("Filtered IM2 Reprojection", folder / "filtered_reprojection_IM2.png"),
            ("Optimized IM0 Reprojection", folder / "optimized_reprojection_IM0.png"),
            ("Optimized IM2 Reprojection", folder / "optimized_reprojection_IM2.png"),
        ]
        return [(label, path) for label, path in candidates if path.exists()]

    def update_overlay_image(self):
        if self.combo_overlay.count() == 0:
            self.lbl_overlay.setText("No validation image found beside this OBJ.")
            self.lbl_overlay.setPixmap(QPixmap())
            return
        path = Path(self.combo_overlay.currentData())
        pixmap = QPixmap(str(path))
        if pixmap.isNull():
            self.lbl_overlay.setText(f"Failed to load:\n{path}")
            return
        scaled = pixmap.scaled(self.lbl_overlay.size(), Qt.KeepAspectRatio, Qt.SmoothTransformation)
        self.lbl_overlay.setPixmap(scaled)

    def resizeEvent(self, event):
        super().resizeEvent(event)
        self.update_overlay_image()

    def render_mesh(self):
        if not self.mesh:
            return
        self.renderer.RemoveAllViewProps()
        self.branch_actors = {}
        self.all_actors = []

        for part in self.mesh.parts:
            poly = make_polydata(self.mesh.vertices, part.faces)
            mapper = vtk.vtkPolyDataMapper()
            mapper.SetInputData(poly)

            actor = vtk.vtkActor()
            actor.SetMapper(mapper)
            color = MATERIAL_COLORS.get(part.material, (0.78, 0.78, 0.78))
            actor.GetProperty().SetColor(*color)
            actor.GetProperty().SetSpecular(0.28)
            actor.GetProperty().SetSpecularPower(22)
            actor.GetProperty().SetInterpolationToPhong()

            self.renderer.AddActor(actor)
            self.all_actors.append(actor)
            branch_id = branch_id_from_name(part.name)
            if branch_id is not None:
                self.branch_actors.setdefault(branch_id, []).append(actor)

        self.add_orientation_marker()

        self.reset_camera()

    def add_orientation_marker(self):
        if self.orientation_widget is not None:
            self.orientation_widget.EnabledOff()

        axes = vtk.vtkAxesActor()
        axes.SetTotalLength(1.0, 1.0, 1.0)
        axes.SetShaftTypeToCylinder()
        axes.SetCylinderRadius(0.035)
        axes.SetConeRadius(0.16)
        axes.SetSphereRadius(0.18)

        for caption in (
            axes.GetXAxisCaptionActor2D(),
            axes.GetYAxisCaptionActor2D(),
            axes.GetZAxisCaptionActor2D(),
        ):
            caption.GetCaptionTextProperty().SetColor(1.0, 1.0, 1.0)
            caption.GetCaptionTextProperty().SetFontSize(14)
            caption.GetCaptionTextProperty().BoldOn()

        self.orientation_widget = vtk.vtkOrientationMarkerWidget()
        self.orientation_widget.SetOrientationMarker(axes)
        self.orientation_widget.SetInteractor(self.interactor)
        # Viewport coordinates are normalized: xmin, ymin, xmax, ymax.
        self.orientation_widget.SetViewport(0.82, 0.78, 0.98, 0.98)
        self.orientation_widget.SetEnabled(1)
        self.orientation_widget.InteractiveOff()

    def visible_bounds_center_span(self):
        bounds = [0.0] * 6
        self.renderer.ComputeVisiblePropBounds(bounds)
        if not all(math.isfinite(value) for value in bounds):
            bounds = [-50.0, 50.0, -50.0, 50.0, -50.0, 50.0]
        if bounds[0] > bounds[1] or bounds[2] > bounds[3] or bounds[4] > bounds[5]:
            bounds = [-50.0, 50.0, -50.0, 50.0, -50.0, 50.0]
        center = (
            (bounds[0] + bounds[1]) * 0.5,
            (bounds[2] + bounds[3]) * 0.5,
            (bounds[4] + bounds[5]) * 0.5,
        )
        span = max(bounds[1] - bounds[0], bounds[3] - bounds[2], bounds[5] - bounds[4], 1.0)
        return center, span

    def set_absolute_camera(self, direction, view_up, scale_factor: float = 0.62, distance_factor: float = 3.0):
        if np is None:
            QMessageBox.warning(self, "Missing Dependency", "NumPy is required for camera controls.")
            return

        center_tuple, span = self.visible_bounds_center_span()
        center = np.array(center_tuple, dtype=float)
        direction_vec = np.asarray(direction, dtype=float)
        up_vec = np.asarray(view_up, dtype=float)

        direction_norm = np.linalg.norm(direction_vec)
        up_norm = np.linalg.norm(up_vec)
        if direction_norm < 1e-6 or up_norm < 1e-6:
            return
        direction_vec = direction_vec / direction_norm
        up_vec = up_vec / up_norm

        # Remove any up-vector component along the view direction to avoid
        # VTK camera roll instability.
        up_vec = up_vec - direction_vec * float(np.dot(up_vec, direction_vec))
        up_norm = np.linalg.norm(up_vec)
        if up_norm < 1e-6:
            up_vec = np.array([0.0, 1.0, 0.0], dtype=float)
        else:
            up_vec = up_vec / up_norm

        camera_position = center - direction_vec * span * distance_factor
        camera = self.renderer.GetActiveCamera()
        camera.ParallelProjectionOn()
        camera.SetFocalPoint(float(center[0]), float(center[1]), float(center[2]))
        camera.SetPosition(float(camera_position[0]), float(camera_position[1]), float(camera_position[2]))
        camera.SetViewUp(float(up_vec[0]), float(up_vec[1]), float(up_vec[2]))
        camera.SetParallelScale(span * scale_factor)
        self.renderer.ResetCameraClippingRange()
        self.vtk_widget.GetRenderWindow().Render()

    def apply_image_orientation(self, direction, view_up):
        if np is None:
            return direction, view_up

        direction_vec = np.asarray(direction, dtype=float)
        up_vec = np.asarray(view_up, dtype=float)
        direction_norm = np.linalg.norm(direction_vec)
        up_norm = np.linalg.norm(up_vec)
        if direction_norm < 1e-6 or up_norm < 1e-6:
            return direction, view_up

        direction_vec = direction_vec / direction_norm
        up_vec = up_vec / up_norm
        right_vec = np.cross(direction_vec, up_vec)
        right_norm = np.linalg.norm(right_vec)
        if right_norm < 1e-6:
            return direction, view_up
        right_vec = right_vec / right_norm

        mode = self.combo_image_orientation.currentText()
        if mode == "Rotate 180":
            up_vec = -up_vec
        elif mode == "Mirror H":
            direction_vec = -direction_vec
        elif mode == "Mirror V":
            direction_vec = -direction_vec
            up_vec = -up_vec
        elif mode == "Mirror H + Rotate 180":
            direction_vec = -direction_vec
            up_vec = -up_vec
        elif mode == "Mirror V + Rotate 180":
            direction_vec = -direction_vec
        elif mode == "Opposite Side":
            direction_vec = -direction_vec
        elif mode == "Opposite Side + Rotate 180":
            direction_vec = -direction_vec
            up_vec = -up_vec

        return direction_vec, up_vec

    def reset_camera(self):
        self.set_absolute_camera(direction=(0.72, -0.46, -0.52), view_up=(-0.28, 0.33, -0.90), scale_factor=0.72)

    def set_im0_like_view(self):
        self.set_summary_angle_view("view_a")

    def update_angle_controls_from_summary(self):
        view = self.summary.get("view_a") if isinstance(self.summary, dict) else None
        if not isinstance(view, dict):
            return
        try:
            self.spin_primary.setValue(float(view.get("primary_angle_deg", 0.0)))
            self.spin_secondary.setValue(float(view.get("secondary_angle_deg", 0.0)))
        except Exception:
            return

    @staticmethod
    def rotation_from_angles(primary_deg: float, secondary_deg: float):
        if np is None:
            raise RuntimeError("NumPy is required for angle-based camera views.")

        primary = math.radians(primary_deg)
        secondary = math.radians(secondary_deg)
        cp, sp = math.cos(primary), math.sin(primary)
        cs, ss = math.cos(secondary), math.sin(secondary)

        rotate_primary = np.array(
            [
                [cp, 0.0, sp],
                [0.0, 1.0, 0.0],
                [-sp, 0.0, cp],
            ],
            dtype=float,
        )
        rotate_secondary = np.array(
            [
                [1.0, 0.0, 0.0],
                [0.0, cs, -ss],
                [0.0, ss, cs],
            ],
            dtype=float,
        )
        return rotate_primary @ rotate_secondary

    def set_camera_from_angles(self, primary_deg: float, secondary_deg: float):
        if not self.all_actors:
            return
        if np is None:
            QMessageBox.warning(self, "Missing Dependency", "NumPy is required for angle-based camera views.")
            return

        rotation = self.rotation_from_angles(primary_deg, secondary_deg)
        source_direction = rotation @ np.array([0.0, 0.0, -1.0], dtype=float)
        detector_up = rotation @ np.array([0.0, 1.0, 0.0], dtype=float)
        source_direction, detector_up = self.apply_image_orientation(source_direction, detector_up)
        self.set_absolute_camera(source_direction, detector_up, scale_factor=0.62, distance_factor=3.0)

    def set_summary_angle_view(self, key: str):
        view = self.summary.get(key) if isinstance(self.summary, dict) else None
        if not isinstance(view, dict):
            QMessageBox.information(self, "No DICOM Angle", f"No {key} angle found beside this OBJ.")
            return
        try:
            primary = float(view.get("primary_angle_deg", 0.0))
            secondary = float(view.get("secondary_angle_deg", 0.0))
        except Exception:
            QMessageBox.warning(self, "Invalid DICOM Angle", f"The {key} angle values are not numeric.")
            return
        self.spin_primary.setValue(primary)
        self.spin_secondary.setValue(secondary)
        self.set_camera_from_angles(primary, secondary)

    def apply_manual_angle_view(self):
        self.set_camera_from_angles(self.spin_primary.value(), self.spin_secondary.value())

    def highlight_selected_branch(self):
        selected_items = self.table.selectedItems()
        selected_branch = None
        if selected_items:
            selected_branch = self.table.item(selected_items[0].row(), 0).data(Qt.UserRole)

        for branch_id, actors in self.branch_actors.items():
            for actor in actors:
                base_status = self.status_from_parts(branch_id)
                base_color = MATERIAL_COLORS.get(base_status, (0.78, 0.78, 0.78))
                if selected_branch is not None and branch_id == selected_branch:
                    actor.GetProperty().SetColor(1.0, 0.05, 0.05)
                    actor.GetProperty().SetSpecular(0.5)
                    actor.GetProperty().SetOpacity(1.0)
                else:
                    actor.GetProperty().SetColor(*base_color)
                    actor.GetProperty().SetSpecular(0.28)
                    actor.GetProperty().SetOpacity(1.0)
        self.vtk_widget.GetRenderWindow().Render()


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--obj", type=Path, default=DEFAULT_OBJ)
    return parser.parse_args()


def main():
    args = parse_args()
    os.environ.setdefault("QT_ENABLE_HIGHDPI_SCALING", "1")
    app = QApplication(sys.argv)
    viewer = VTKArteryViewer(args.obj)
    viewer.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
